
//  (C) Copyright Edward Diener 2016
//  Use, modification and distribution are subject to the Boost Software License,
//  Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at
//  http://www.boost.org/LICENSE_1_0.txt).

#define CXXD_ARRAY_USE_STD
#define CXXD_ATOMIC_USE_STD
#define CXXD_BIND_USE_STD
#define CXXD_CHRONO_USE_STD
#define CXXD_CONDITION_VARIABLE_USE_STD
#define CXXD_ENABLE_SHARED_FROM_THIS_USE_STD
#define CXXD_FUNCTION_USE_STD
#define CXXD_HASH_USE_STD
#define CXXD_MAKE_SHARED_USE_STD
#define CXXD_MEM_FN_USE_STD
#define CXXD_MUTEX_USE_STD
#define CXXD_RANDOM_USE_STD
#define CXXD_RATIO_USE_STD
#define CXXD_REF_USE_STD
#define CXXD_REGEX_USE_STD
#define CXXD_SHARED_MUTEX_USE_STD
#define CXXD_SHARED_PTR_USE_STD
#define CXXD_SYSTEM_ERROR_USE_STD
#define CXXD_THREAD_USE_STD
#define CXXD_TUPLE_USE_STD
#define CXXD_TYPE_INDEX_USE_STD
#define CXXD_TYPE_TRAITS_USE_STD
#define CXXD_UNORDERED_MAP_USE_STD
#define CXXD_UNORDERED_MULTIMAP_USE_STD
#define CXXD_UNORDERED_MULTISET_USE_STD
#define CXXD_UNORDERED_SET_USE_STD
#define CXXD_WEAK_PTR_USE_STD
