//  (C) Copyright Edward Diener 2016. 
//  Use, modification and distribution are subject to the 
//  Boost Software License, Version 1.0. (See accompanying file 
//  LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

#if !defined(CXXD_DETAIL_MOD_TABLE_HPP)
#define CXXD_DETAIL_MOD_TABLE_HPP

#include <boost/cxxd/detail/library_name_register.hpp>

#define CXXD_DETAIL_MOD_TABLE
    (
    (CXXD_ID_ARRAY,CXXD_HAS_STD_ARRAY),
    (CXXD_ID_ATOMIC,CXXD_HAS_STD_ATOMIC),
    (CXXD_ID_BIND,CXXD_HAS_STD_BIND),
    (CXXD_ID_CHRONO,CXXD_HAS_STD_CHRONO),
    (CXXD_ID_CONDITION_VARIABLE,CXXD_HAS_STD_CONDITION_VARIABLE),
    (CXXD_ID_FUNCTION,CXXD_HAS_STD_FUNCTION),
    (CXXD_ID_HASH,CXXD_HAS_STD_HASH),
    (CXXD_ID_MEM_FN,CXXD_HAS_STD_MEM_FN),
    (CXXD_ID_MUTEX,CXXD_HAS_STD_MUTEX),
    (CXXD_ID_RANDOM,CXXD_HAS_STD_RANDOM),
    (CXXD_ID_RATIO,CXXD_HAS_STD_RATIO),
    (CXXD_ID_REF,CXXD_HAS_STD_REF),
    (CXXD_ID_REGEX,CXXD_HAS_STD_REGEX),
    (CXXD_ID_SHARED_MUTEX,CXXD_HAS_STD_SHARED_MUTEX),
    (CXXD_ID_SHARED_PTR,CXXD_HAS_STD_SHARED_PTR),
    (CXXD_ID_SYSTEM,CXXD_HAS_STD_SYSTEM),
    (CXXD_ID_THREAD,CXXD_HAS_STD_THREAD),
    (CXXD_ID_TUPLE,CXXD_HAS_STD_TUPLE),
    (CXXD_ID_TYPE_INDEX,CXXD_HAS_STD_TYPE_INDEX),
    (CXXD_ID_TYPE_TRAITS,CXXD_HAS_STD_TYPE_TRAITS),
    (CXXD_ID_UNORDERED_MAP,CXXD_HAS_STD_UNORDERED_MAP),
    (CXXD_ID_UNORDERED_MULTIMAP,CXXD_HAS_STD_UNORDERED_MULTIMAP),
    (CXXD_ID_UNORDERED_MULTISET,CXXD_HAS_STD_UNORDERED_MULTISET),
    (CXXD_ID_UNORDERED_SET,CXXD_HAS_STD_UNORDERED_SET)
    )

#endif // !defined(CXXD_DETAIL_MOD_TABLE_HPP)
