//  (C) Copyright Edward Diener 2016. 
//  Use, modification and distribution are subject to the 
//  Boost Software License, Version 1.0. (See accompanying file 
//  LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

#if !defined(CXXD_DETAIL_MOD_TABLE_HPP)
#define CXXD_DETAIL_MOD_TABLE_HPP

#define CXXD_DETAIL_MOD_TABLE \
    ( \
    (CXXD_ARRAY,CXXD_HAS_STD_ARRAY), \
    (CXXD_ATOMIC,CXXD_HAS_STD_ATOMIC), \
    (CXXD_BIND,CXXD_HAS_STD_BIND), \
    (CXXD_CHRONO,CXXD_HAS_STD_CHRONO), \
    (CXXD_CONDITION_VARIABLE,CXXD_HAS_STD_CONDITION_VARIABLE), \
    (CXXD_ENABLE_SHARED_FROM_THIS,CXXD_HAS_STD_ENABLE_SHARED_FROM_THIS), \
    (CXXD_FUNCTION,CXXD_HAS_STD_FUNCTION), \
    (CXXD_HASH,CXXD_HAS_STD_HASH), \
    (CXXD_MAKE_SHARED,CXXD_HAS_STD_MAKE_SHARED), \
    (CXXD_MEM_FN,CXXD_HAS_STD_MEM_FN), \
    (CXXD_MOVE,CXXD_HAS_STD_MOVE), \
    (CXXD_MUTEX,CXXD_HAS_STD_MUTEX), \
    (CXXD_RANDOM,CXXD_HAS_STD_RANDOM), \
    (CXXD_RATIO,CXXD_HAS_STD_RATIO), \
    (CXXD_REF,CXXD_HAS_STD_REF), \
    (CXXD_REGEX,CXXD_HAS_STD_REGEX), \
    (CXXD_SHARED_MUTEX,CXXD_HAS_STD_SHARED_MUTEX), \
    (CXXD_SHARED_PTR,CXXD_HAS_STD_SHARED_PTR), \
    (CXXD_SYSTEM_ERROR,CXXD_HAS_STD_SYSTEM_ERROR), \
    (CXXD_THREAD,CXXD_HAS_STD_THREAD), \
    (CXXD_TUPLE,CXXD_HAS_STD_TUPLE), \
    (CXXD_TYPE_INDEX,CXXD_HAS_STD_TYPE_INDEX), \
    (CXXD_TYPE_TRAITS,CXXD_HAS_STD_TYPE_TRAITS), \
    (CXXD_UNORDERED_MAP,CXXD_HAS_STD_UNORDERED_MAP), \
    (CXXD_UNORDERED_MULTIMAP,CXXD_HAS_STD_UNORDERED_MULTIMAP), \
    (CXXD_UNORDERED_MULTISET,CXXD_HAS_STD_UNORDERED_MULTISET), \
    (CXXD_UNORDERED_SET,CXXD_HAS_STD_UNORDERED_SET), \
    (CXXD_WEAK_PTR,CXXD_HAS_STD_WEAK_PTR) \
    ) \
/**/

#endif // !defined(CXXD_DETAIL_MOD_TABLE_HPP)
